project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path
from recipes import views

app_name = 'recipes'

urlpatterns = [
    path('recipes/<int:id>/', views.recipes, name='recipe'),
    path('recipes/category/<int:id>/', views.category, name='category'),
    path('', views.home, name='home'),
]

recipes/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self) -> str:
        return self.name


class Recipe(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField()
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=20)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=20)
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(upload_to='recipes/covers/%Y/%m/%d/')
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, blank=True,
        default=None
    )
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True
    )

    def __str__(self) -> str:
        return self.title

recipes/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404
from django.utils.translation import gettext as _
from django.utils import translation
from recipes.models import Recipe

html_language = translation.get_language()


def home(request):
    recipes = get_list_or_404(
        Recipe.objects.filter(is_published=True).order_by('-id')
    )

    return render(request, "recipes/pages/home.html", context={
        'html_language': html_language,
        'title': 'Home',
        'recipes': recipes,
    })


def category(request, id):
    recipes = get_list_or_404(
        Recipe.objects.filter(
            category__id=id, is_published=True
        ).order_by('-id')
    )
    title = _('Category')

    return render(request, "recipes/pages/home.html", context={
        'html_language': html_language,
        'title': f'{title} - {recipes[0].category.name}',
        'recipes': recipes,
    })


def recipes(request, id: int):
    recipe = get_object_or_404(
        Recipe.objects.filter(id=id, is_published=True)
    )
    title: str = _('Recipe')

    return render(request, "recipes/pages/recipes-view.html", context={
        'html_language': html_language,
        'title': f'{title}: {recipe.title}',
        'recipe': recipe,
        'is_detail_page': True,
    })

recipes/templates/recipes/pages/home.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="main-content main-content-list container">
    {% for recipe in recipes %}
      {% include 'recipes/partials/_main_list.html' %}
    {% endfor %}
  </div>
{% endblock content %}

recipes/templates/recipes/pages/recipes-view.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="main-content main-content-detail container">
    {% include 'recipes/partials/_main_list.html' %}
  </div>
{% endblock content %}

recipes/templates/recipes/partials/_footer.html
<footer class="main-footer">
  <div class="footer-container">
    <div class="footer-dev">
      <a href="https://linktr.ee/ruangemmer" target="_blank" rel="noopener noreferrer">By Ruan Gemmer</a>
    </div>
    <div class="footer-software">
      <a href="https://www.djangoproject.com/" target="_blank" rel="noopener noreferrer">Powered by Django</a>
    </div>
  </div>
</footer>

recipes/templates/recipes/partials/_head.html
{% load static %}

<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/fontawesome.min.css" integrity="sha512-siarrzI1u3pCqFG2LEzi87McrBmq6Tp7juVsdmGY1Dr8Saw+ZBAzDzrGwX3vgxX1NkioYNCFOVC0GpDPss10zQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/brands.min.css" integrity="sha512-W/zrbCncQnky/EzL+/AYwTtosvrM+YG/V6piQLSe2HuKS6cmbw89kjYkp3tWFn1dkWV7L1ruvJyKbLz73Vlgfg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/solid.min.css" integrity="sha512-P9pgMgcSNlLb4Z2WAB2sH5KBKGnBfyJnq+bhcfLCFusrRc4XdXrhfDluBl/usq75NF5gTDIMcwI1GaG5gju+Mw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">

<link rel="stylesheet" href="{% static 'global/css/remedy.css' %}">
<link rel="stylesheet" href="{% static 'recipes/css/styles.css' %}">

recipes/templates/recipes/partials/_header.html
{% load i18n %}
<header class="main-header-container">
    <div class="main-header container">
      <h1>
        <a href="{% url 'recipes:home' %}" class="main-logo">
          <i class="fa-solid fa-utensils main-logo-icon"></i> 
          <span class="main-logo-text">
            {% trans "Recipes" %}
          </span>
        </a>
    </h1>
        
    </div>
</header>

recipes/templates/recipes/partials/_main_list.html
{% load i18n %}

    <div class="recipe recipe-list-item">
      <div class="recipe-cover">
        {% if is_detail_page is not True %}
          <a href="{% url 'recipes:recipe' recipe.id %}">
            <img src="{{recipe.cover.url}}" alt="Temp" />
          </a>
        {% else %}
          <img src="{{recipe.cover.url}}" alt="Temp" />
        {% endif %}
      </div>

      <div class="recipe-title-container">
        <h2 class="recipe-title">
          {% if is_detail_page is not True %}
            <a href="{% url 'recipes:recipe' recipe.id %}">
              {{recipe.title}}
            </a>
          {% else %}
            {{recipe.title}}  
          {% endif %}
        </h2>
      </div>

      <div class="recipe-author">
        <span class="recipe-author-item">
          <i class="fas fa-user"></i>
            {% if recipe.author is not None %}
              {% if recipe.author.first_name %}
                {{recipe.author.first_name}} {{recipe.author.last_name}}
              {% else %}
                {{recipe.username}}
              {% endif %}
            {% else %}
              Desconhecido
            {% endif %}
          </span>
        <span class="recipe-author-item">
          <i class="fas fa-calendar-alt"></i>
          {{recipe.created_at|date:"d/m/Y"}}
        </span>
        {% if recipe.category is not None %}
          <span class="recipe-author-item">
            <a href="{% url 'recipes:category' recipe.category.id %}">
              <i class="fas fa-layer-group"></i>
              <span>{{recipe.category.name}}</span>
            </a>
          </span>
        {% endif %}
      </div>

      <div class="recipe-content">
        <p>{{recipe.description}}</p>
      </div>

      <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
          <h3 class="recipe-meta-title">
            <i class="fas fa-stopwatch"></i>
            {% trans 'Preparation' %}
          </h3>
          <div class="recipe-meta-text">
            {{recipe.preparation_time}} {{recipe.preparation_time_unit}}
          </div>
        </div>
        <div class="recipe-meta recipe-servings">
          <h3 class="recipe-meta-title">
            <i class="fas fa-pizza-slice"></i>
            {% trans 'Servings' %}
          </h3>
          <div class="recipe-meta-text">
            {{recipe.servings}} {{recipe.servings_unit}}
          </div>
        </div>
      </div>
      
      {% if is_detail_page is not True %}
        <button class="recipe-button">
          <a href="{% url 'recipes:recipe' recipe.id %}" class="recipe-read-more button button-dark button-full-width">
            <i class="fa-solid fa-eye"></i>
            <span>{% trans 'Read more' %}...</span>
          </a>
        </button>
      {% endif %}

      {% if is_detail_page is True %}
        <div class="preparation-steps">
          {% if recipe.preparation_steps_is_html is True %}
            {{recipe.preparation_steps|safe}}
          {% else %}
            {{recipe.preparation_steps|linebreaksbr}}
          {% endif %}
        </div>
      {% endif %}
    </div>

recipes/templates/recipes/partials/_search.html
{% load i18n %}
<div class="search-container">
    <div class="container">
      <form action="" class="search-form">
        <input type="search" name="search" class="search-input" autocomplete="off" placeholder="{% trans "Type something to search" %}...">
        <button type="submit" class="search-button">
          <i class="fa-solid fa-magnifying-glass"></i>
        </button>
      </form>
    </div>
  </div>